Allow jruby failures?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,7 @@ on:
 jobs:
   tests:
     runs-on: ubuntu-latest
+    continue-on-error: ${{ matrix.optional }}
     strategy:
       fail-fast: false
       matrix:
@@ -17,10 +18,14 @@ jobs:
           - "3.4"
           - "3.3"
           - "3.2"
-          - "jruby"
         rack:
           - "~> 2.0"
           - "~> 3.0"
+        optional: [false]
+        include:
+          - ruby: "jruby"
+            rack: "~> 3.0"
+            optional: true
     name: tests (Ruby ${{ matrix.ruby }}, Rack ${{ matrix.rack }})
     steps:
       - uses: actions/checkout@v1
@@ -34,9 +39,27 @@ jobs:
         env:
           RACK_VERSION_CONSTRAINT: ${{matrix.rack}}
       - name: Run all tests
-        run: script/ci
+        run: |
+          status=0
+          script/ci || status=$?
+          if [ ${status} -ne 0 ] && [ "${{ matrix.optional }}" == "true" ]; then
+            echo "::warning::Optional matrix job failed."
+            echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
+            echo "optional_fail_status=${status}" >> "${GITHUB_OUTPUT}"
+            exit 0  # Ignore error here to keep the green checkmark going
+          fi
+          exit ${status}
         env:
           RACK_VERSION_CONSTRAINT: ${{matrix.rack}}
+      - name: Comment for optional failures
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ matrix.optional }}
+        with:
+          # Note: tag must be unique to each matrix case
+          comment-tag: "${{ matrix.ruby }}-${{ matrix.rack }}-optional-notice"
+          message: |
+            **⚠️ Optional matrix job Ruby ${{ matrix.ruby }} - Rack ${{ matrix.rack }} failed**
+          mode: ${{ steps.test.outputs.optional_fail == 'true' && 'upsert' || 'delete' }}
 
   workflow-keepalive:
     if: github.event_name == 'schedule'
